import { assets } from "../assets/assets";


export const products = [

  
 {
    "id": 1,
    "name": "2½\" Kuruvi",
    "price": 30,
    "image": assets.birdCrackers,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 2,
    "name": "3½\" Lakshmi",
    "price": 45,
    "image": assets.lakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 3,
    "name": "4\" Lakshmi",
    "price": 75,
    "image": assets.lakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 4,
    "name": "4\" Deluxe Lakshmi",
    "price": 100,
    "image": assets.lakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 5,
    "name": "4\" Gold Lakshmi",
    "price": 140,
    "image": assets.goldlakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 6,
    "name": "5\" Deluxe Lakshmi",
    "price": 200,
    "image": assets.lakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 7,
    "name": "6\" Deluxe Lakshmi",
    "price": 220,
    "image": assets.lakshmi,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 8,
    "name": "Two Sound",
    "price": 180,
    "image": assets.twosound,
    "category": "ONE SOUND CRACKERS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 9,
    "name": "Flower Pots Big ",
    "price": 250,
    "image": assets.potbig,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 10,
    "name": "Flower Pots Special",
    "price": 350,
    "image": assets.potspl,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 11,
    "name": "Flower Pots Ashoka (Mithran)",
    "price": 450,
    "image": assets.potaso,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 12,
    "name": "Flower Pots Big ",
    "price": 300,
    "image": assets.potbig,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 13,
    "name": "Flower Pots Special (Iniyas)",
    "price": 400,
    "image": assets.potspl,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 14,
    "name": "Flower Pots Ashoka (Iniyas)",
    "price": 450,
    "image": assets.potaso,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 15,
    "name": "Colour Koti",
    "price": 800,
    "image": assets.koti,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 16,
    "name": "Colour Koti Super Giant",
    "price": 1400,
    "image": assets.kotig,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 17,
    "name": "Colour Koti Jumbo",
    "price": 2400,
    "image": assets.kotij,
    "category": "FLOWER POTS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 18,
    "name": "Ground chakkar Big",
    "price": 220,
    "image": assets.chakarbig,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 19,
    "name": "Ground chakkar Special",
    "price": 350,
    "image": assets.chakarspl,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 20,
    "name": "Ground chakkar Deluxe",
    "price": 600,
    "image": assets.chakard,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 21,
    "name": "4 x 4 Wheel",
    "price": 700,
    "image": assets.wheel4,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 22,
    "name": "Wire chakkar",
    "price": 950,
    "image": assets.wire,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 23,
    "name": "Racing Wheel",
    "price": 700,
    "image": assets.racing,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 24,
    "name": "Disco Wheel",
    "price": 900,
    "image": assets.disco,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 25,
    "name": "Ruby Colour Wheel",
    "price": 900,
    "image": assets.ruby,
    "category": "GROUND CHAKKAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 26,
    "name": "1¾\" Twinkling Star",
    "price": 90,
    "image": assets.twin1,
    "category": "TWINKLING STAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 27,
    "name": "4\" Twinkling Star",
    "price": 250,
    "image": assets.twin2,
    "category": "TWINKLING STAR",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 28,
    "name": "Little Heart",
    "price": 160,
    "image": assets.chit,
    "category": "CHIT PUT",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 29,
    "name": "Tik Tok",
    "price": 200,
    "image": assets.chit,
    "category": "CHIT PUT",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 30,
    "name": "Hydro Bomb",
    "price": 350,
    "image": assets.hydro,
    "category": "BOMBS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 31,
    "name": "Bullet Bomb",
    "price": 90,
    "image": assets.bullet,
    "category": "BOMBS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 32,
    "name": "Classic Bomb",
    "price": 580,
    "image": assets.classic,
    "category": "BOMBS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 33,
    "name": "Digital Bomb",
    "price": 1000,
    "image": assets.digitalbomb,
    "category": "BOMBS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 34,
    "name": "Hakker Bomb",
    "price": 1400,
    "image": assets.hacker,
    "category": "BOMBS",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 35,
    "name": "Peacock Feather",
    "price": 600,
    "image": assets.peacockf,
    "category": "PEACOCK FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 36,
    "name": "Peacock Feather (3 Face)",
    "price": 700,
    "image": assets.peacock,
    "category": "PEACOCK FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 37,
    "name": "Bada Peacock",
    "price": 1800,
    "image": assets.badap,
    "category": "PEACOCK FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 38,
    "name": "Bada Peacock (Multi Colour)",
    "price": 2000,
    "image": assets.badap,
    "category": "PEACOCK FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 39,
    "name": "Popcorn Pencil (3 Pcs)",
    "price": 800,
    "image": assets.popcornpencil,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 40,
    "name": "Traffic Master (5 Pcs)",
    "price": 750,
    "image": assets.traffic,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 41,
    "name": "Sivakasi Special (2 Pcs)",
    "price": 800,
    "image": assets.sivakasi,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 42,
    "name": "Star Falls (3 Pcs)",
    "price": 600,
    "image": assets.starfall,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 43,
    "name": "Pop Hot (3 Pcs)",
    "price": 600,
    "image": assets.pophot,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 44,
    "name": "Wolverin Pencil (5 Pcs)",
    "price": 600,
    "image": assets.wol,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 45,
    "name": "Water Fall (5 Pcs)",
    "price": 650,
    "image": assets.waterfall,
    "category": "MULTI COLOUR PENCIL",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 46,
    "name": "Shinchan(3 Pcs)",
    "price": 550,
    "image": assets.shingchan,
    "category": "TRI COLOUR FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 47,
    "name": "Tri Colour Mega (5 Pcs)",
    "price": 1200,
    "image": assets.tri,
    "category": "TRI COLOUR FOUNTAIN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 48,
    "name": "Unicorn (Water Queen)",
    "price": 800,
    "image": assets.Unicorn,
    "category": "WATER QUEEN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 49,
    "name": "6\" T-20 (Water Party)",
    "price": 650,
    "image": assets.water,
    "category": "WATER QUEEN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 50,
    "name": "Dragon Warrior (1 Pcs)",
    "price": 500,
    "image": assets.dragon,
    "category": "WATER QUEEN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 51,
    "name": "Touch me Falls",
    "price": 650,
    "image": assets.touch,
    "category": "WATER QUEEN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 52,
    "name": "H₂O Gun",
    "price": 850,
    "image": assets.h20,
    "category": "WATER QUEEN",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 53,
    "name": "Rocket Bomb",
    "price": 300,
    "image": assets.rocketbomb,
    "category": "ROCKET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 54,
    "name": "Two Sound Rocket",
    "price": 450,
    "image": assets.tworocket,
    "category": "ROCKET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 55,
    "name": "Musical Rocket",
    "price": 550,
    "image": assets.rocket2,
    "category": "ROCKET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 56,
    "name": "Prediator Special",
    "price": 1200,
    "image": assets.pred,
    "category": "ROCKET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 57,
    "name": "Red Bijili (Half Counting)",
    "price": 70,
    "image": assets.bijilired,
    "category": "BIJILI",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 58,
    "name": "Stripped Bijili (Half Counting)",
    "price": 80,
    "image": assets.stripped,
    "category": "BIJILI",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 59,
    "name": "Red Bijili (full Counting)",
    "price": 140,
    "image": assets.bijilired,
    "category": "BIJILI",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 60,
    "name": "Stripped Bijili (full Counting)",
    "price": 150,
    "image": assets.stripped,
    "category": "BIJILI",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 61,
    "name": "Magic Pops",
    "price": 30,
    "image": assets.magicpop,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 62,
    "name": "Zee Boom Baa",
    "price": 30,
    "image": assets.jee,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 63,
    "name": "Pogo 2\" Shower",
    "price": 120,
    "image": assets.pogo,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 64,
    "name": "Angry Bird 4\" Shower",
    "price": 250,
    "image": assets.angry,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 65,
    "name": "Butter fly",
    "price": 350,
    "image": assets.butterfly,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 66,
    "name": "90 Watts",
    "price": 550,
    "image": assets.watt,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 67,
    "name": "Pumbaram Spinner (10 Pieces)",
    "price": 475,
    "image": assets.bambara,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 68,
    "name": "Drone (5 Piece)",
    "price": 700,
    "image": assets.drone,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null 
  },
  {
    "id": 69,
    "name": "Photoflash(5 Piece)",
    "price": 300,
    "image": assets.photo,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 70,
    "name": "Helicopter(5 Piece)",
    "price": 450,
    "image": assets.helicopter,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 71,
    "name": "Five Ranger (5 Continuous Fountain)",
    "price": 1200,
    "image": assets.ranger,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 72,
    "name": "Pops and drops (5 Piece)",
    "price": 650,
    "image": assets.pops,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 73,
    "name": "Gold Star (3 Piece)",
    "price": 600,
    "image": assets.goldstar,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 74,
    "name": "Silver Star (3 Piece)",
    "price": 600,
    "image": assets.silverstar,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 75,
    "name": "Red Star (3 Piece)",
    "price": 600,
    "image": assets.greenstar,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 76,
    "name": "Green Star (3 Piece)",
    "price": 600,
    "image": assets.redstar,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 77,
    "name": "Red and Green Star (3 Piece)",
    "price": 700,
    "image": assets.redgreen,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 78,
    "name": "Miss Butterfly (5 Piece)",
    "price": 750,
    "image": assets.missbutter,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 79,
    "name": "Blue ice (5 Piece)",
    "price": 750,
    "image": assets.blueice,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 80,
    "name": "Gold Feast (5 Piece)",
    "price": 750,
    "image": assets.goldfeast,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 81,
    "name": "Red Sun (5 Piece)",
    "price": 800,
    "image": assets.redsun,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 82,
    "name": "Green Garden (5 Piece)",
    "price": 750,
    "image": assets.greengarden,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 83,
    "name": "Crackling Trees (3 Piece)",
    "price": 960,
    "image": assets.crackling,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 84,
    "name": "Rainy & Shiny (3 Piece)",
    "price": 1100,
    "image": assets.rainy,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 85,
    "name": "Tik Tak (3 Piece)",
    "price": 1100,
    "image": assets.tiktak,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 86,
    "name": "Crack Jack (Crackling & Sky Shot)",
    "price": 1100,
    "image": assets.jack,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 87,
    "name": "Selfie Stick",
    "price": 600,
    "image": assets.selfie,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 88,
    "name": "Belly & Jelly",
    "price": 1100,
    "image": assets.belly,
    "category": "NOVELTIES",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 89,
    "name": "Serpent Egg (Sony)",
    "price": 300,
    "image": assets.serpentsony,
    "category": "SNAKE TABLET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 90,
    "name": "Snake Egg",
    "price": 80,
    "image": assets.snake,
    "category": "SNAKE TABLET",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 91,
    "name": "Smoke (3 Piece)",
    "price": 750,
    "image": assets.smoke,
    "category": "SMOKE",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 92,
    "name": "Minions (1 Piece)",
    "price": 150,
    "image": assets.minions,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 93,
    "name": "Prodance(1 Piece)",
    "price": 150,
    "image": assets.prodance,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 94,
    "name": "Panda(1 Piece)",
    "price": 150,
    "image": assets.panda,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 95,
    "name": "Incrediables(1 Piece)",
    "price": 150,
    "image": assets.Incrediables,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 96,
    "name": "Sparten II(1 Piece)",
    "price": 150,
    "image": assets.spartans,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 97,
    "name": "Insta(1 Piece)",
    "price": 150,
    "image": assets.insta,
    "category": "CHOTA FANCY (Single Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 98,
    "name": "Palm Garden (Krishna - 3 Piece)",
    "price": 1000,
    "image": assets.chota98,
    "category": "1% CHOTA FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 99,
    "name": "Lunar Light",
    "price": 500,
    "image": assets.lunar,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 100,
    "name": "Gold Coin",
    "price": 500,
    "image": assets.goldcoin,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 101,
    "name": "Booty Camp",
    "price": 500,
    "image": assets.booty,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 102,
    "name": "King Kohli",
    "price": 500,
    "image": assets.king,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 103,
    "name": "Green Beat",
    "price": 500,
    "image": assets.greenbeat,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 104,
    "name": "Fast & Furious",
    "price": 500,
    "image": assets.fastfury,
    "category": "2\" SINGLE FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 105,
    "name": "Fist Fury",
    "price": 1100,
    "image": assets.fist,
    "category": "2\"FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 106,
    "name": "Trip Lots",
    "price": 1100,
    "image": assets.fancy2,
    "category": "2\"FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
    "id": 107,
    "name": "Thriller",
    "price": 1100,
    "image": assets.thriller,
    "category": "2\"FANCY (3 Pce)",
    "brand": "MANO",
    "rating": null,
    "description": null,
    "color": null
  },
  {
  "id": 108,
  "name": "Golden Sun",
  "price": 1100,
  "image": assets.fancy2,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 109,
  "name": "Red Thunder",
  "price": 1100,
  "image": assets.fancy2,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 110,
  "name": "Ms Dhoni (3 Piece)",
  "price": 1750,
  "image": assets.cricket,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 111,
  "name": "Ravindra Jadeja (3 Piece)",
  "price": 1750,
  "image": assets.cricket,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 112,
  "name": "Virat Kohli (3 Piece)",
  "price": 1750,
  "image": assets.cricket,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 113,
  "name": "Sachin Tendulkar (3 Piece)",
  "price": 1750,
  "image": assets.cricket,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 114,
  "name": "Rohit Sharma (3 Piece)",
  "price": 1750,
  "image": assets.cricket,
  "category": "2\"FANCY (3 Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 115,
  "name": "Dreams (4 in 1)",
  "price": 1800,
  "image": assets.dummy,
  "category": "3\" FANCY (4 in 1) 3 Piece",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 116,
  "name": "Fantasy (4 in 1)",
  "price": 1800,
  "image": assets.dummy,
  "category": "3\" FANCY (4 in 1) 3 Piece",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 117,
  "name": "Gangstar",
  "price": 1200,
  "image": assets.fancy312,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 118,
  "name": "Beauty Queen",
  "price": 1200,
  "image": assets.fancy312,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 119,
  "name": "Grand Master",
  "price": 1200,
  "image": assets.fancy312,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 120,
  "name": "Rock Jack",
  "price": 1200,
  "image": assets.fancy312,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 121,
  "name": "Kanishkar Items",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 122,
  "name": "Namma Chennai",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 123,
  "name": "Parish Queen",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 124,
  "name": "New York",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 125,
  "name": "London",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 126,
  "name": "Dubai Night",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 127,
  "name": "Italian Delight",
  "price": 1400,
  "image": assets.fancy3121,
  "category": "3½\"FANCY (Single Pce)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 128,
  "name": "Dandiya",
  "price": 4500,
  "image": assets.fancy4k,
  "category": "4\"FANCY (2 Pce Kaniskar)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 129,
  "name": "Garba",
  "price": 4500,
  "image": assets.fancy4k,
  "category": "4\"FANCY (2 Pce Kaniskar)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 130,
  "name": "Kathakali",
  "price": 4500,
  "image": assets.fancy4k,
  "category": "4\"FANCY (2 Pce Kaniskar)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 131,
  "name": "Mehndi",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 132,
  "name": "Haldi",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 133,
  "name": "Sangeet",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 134,
  "name": "Sagai",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 135,
  "name": "Shadi",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 136,
  "name": "Svaagat",
  "price": 4900,
  "image": assets.fancy4s,
  "category": "4\"FANCY 2 PIECE (Spanka)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 137,
  "name": "Wow Pink",
  "price": 2200,
  "image": assets.fancypink,
  "category": "4\"SPECIAL COLOUR (Wow Star)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Pink"
},
{
  "id": 138,
  "name": "Wow Pupple",
  "price": 2200,
  "image": assets.fancypurple,
  "category": "4\"SPECIAL COLOUR (Wow Star)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Purple"
},
{
  "id": 139,
  "name": "Aladdin",
  "price": 2200,
  "image": assets.aladin,
  "category": "4\" DOUBLE BALL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 140,
  "name": "Lion King",
  "price": 2200,
  "image": assets.lion,
  "category": "4\" DOUBLE BALL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 141,
  "name": "Rock Dog",
  "price": 2200,
  "image": assets.rockdog,
  "category": "4\" DOUBLE BALL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 142,
  "name": "Duck Duck Goose",
  "price": 2200,
  "image": assets.duck,
  "category": "4\" DOUBLE BALL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 143,
  "name": "Ice Blue",
  "price": 3500,
  "image": assets.iceblue,
  "category": "5'FANCY SINGLE POE",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Blue"
},
{
  "id": 144,
  "name": "Spicy Orange",
  "price": 3500,
  "image": assets.sporange,
  "category": "5'FANCY SINGLE POE",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Orange"
},
{
  "id": 145,
  "name": "Nayagara Night",
  "price": 3500,
  "image": assets.night,
  "category": "5'FANCY SINGLE POE",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 146,
  "name": "Sizzlers",
  "price": 3500,
  "image": assets.sizz,
  "category": "5'FANCY SINGLE POE",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 147,
  "name": "Cracktails",
  "price": 3500,
  "image": assets.crack,
  "category": "5'FANCY SINGLE POE",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 148,
  "name": "12 Shot Square",
  "price": 750,
  "image": assets.shot12s,
  "category": "REPEATING SHOT",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 149,
  "name": "12 Shot Hexzagan",
  "price": 800,
  "image": assets.shot12,
  "category": "REPEATING SHOT",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 150,
  "name": "25 Shot Rider",
  "price": 900,
  "image": assets.shot25,
  "category": "REPEATING SHOT",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 151,
  "name": "50 Shot Rider",
  "price": 1800,
  "image": assets.shot50,
  "category": "REPEATING SHOT",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 152,
  "name": "100 Shot Rider",
  "price": 4000,
  "image": assets.shot100,
  "category": "REPEATING SHOT",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 153,
  "name": "15 Shot (Multi Colour)",
  "price": 1100,
  "image": assets.shot15,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 154,
  "name": "25 Shot Yummy (Multi Colour)",
  "price": 1500,
  "image": assets.shot25m,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 155,
  "name": "30 Shot (Multi Colour)",
  "price": 1800,
  "image": assets.shot30,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 156,
  "name": "50 Shot (Temptution)",
  "price": 3000,
  "image": assets.shot50t,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 157,
  "name": "60 Shot (Multi Colour)",
  "price": 3500,
  "image": assets.shot60,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 158,
  "name": "108 Shot (Manthra)",
  "price": 5500,
  "image": assets.dummy,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 159,
  "name": "Olympus (150 Shot)",
  "price": 7000,
  "image": assets.dummy,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 160,
  "name": "120 Shot",
  "price": 7000,
  "image": assets.shot120,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 161,
  "name": "240 Shot",
  "price": 14000,
  "image": assets.shot240,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 162,
  "name": "2½ Mega Setout (20 Shot)",
  "price": 15000,
  "image": assets.setout,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 163,
  "name": "25 Troy (Sony)",
  "price": 2600,
  "image": assets.troysony,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 164,
  "name": "Lion King (Sony)",
  "price": 2600,
  "image": assets.sonylion,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 165,
  "name": "Gladiator (50 Shot Sony)",
  "price": 5500,
  "image": assets.gladysony,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 166,
  "name": "Avatar (50 Shot Sony)",
  "price": 5500,
  "image": assets.avatarsony,
  "category": "MULTI COLOUR SHOTS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 167,
  "name": "Circus (8 in 1 Chakkar)",
  "price": 750,
  "image": assets.circus,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 168,
  "name": "Hand Cone",
  "price": 1500,
  "image": assets.handcone,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 169,
  "name": "Hand shooter (15 Shot)",
  "price": 3500,
  "image": assets.hand,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 170,
  "name": "Guitar",
  "price": 800,
  "image": assets.guitar,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 171,
  "name": "Kadayutham",
  "price": 800,
  "image": assets.kadha,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 172,
  "name": "Love Dose (6 Shot in multicolour)",
  "price": 650,
  "image": assets.love,
  "category": "NEW ARRIVALS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 173,
  "name": "Little Joy",
  "price": 4000,
  "image": assets.littlesony,
  "category": "PARTY SPECIAL (4 x 5 Sony)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 174,
  "name": "Ant Man",
  "price": 4000,
  "image": assets.antsony,
  "category": "PARTY SPECIAL (4 x 5 Sony)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 175,
  "name": "Genesys",
  "price": 4000,
  "image": assets.genesy,
  "category": "PARTY SPECIAL (4 x 5 Sony)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 176,
  "name": "¼ Kg Paper Bomb",
  "price": 180,
  "image": assets.paperbomb,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 177,
  "name": "½ Kg Paper Bomb",
  "price": 360,
  "image": assets.paperbomb,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 178,
  "name": "1Kg Paper Bomb",
  "price": 720,
  "image": assets.paperbomb,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 179,
  "name": "Magic Show (Success)",
  "price": 900,
  "image": assets.magicshow,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 180,
  "name": "Magic Show (SONY)",
  "price": 1800,
  "image": assets.magicmono,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 181,
  "name": "Money Bank (3pcs)",
  "price": 900,
  "image": assets.money3p,
  "category": "MARRIAGE PARTY SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 182,
  "name": "Siren (2 Pce)",
  "price": 500,
  "image": assets.siren2p,
  "category": "SIREN",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 183,
  "name": "Mini Siren (5 Pce)",
  "price": 600,
  "image": assets.siren5p,
  "category": "SIREN",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 184,
  "name": "Siren (3 Pce)",
  "price": 800,
  "image": assets.siren3p,
  "category": "SIREN",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 185,
  "name": "Sweet Sixteen (Wizzling Shot)",
  "price": 1900,
  "image": assets.sweet,
  "category": "SIREN",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 186,
  "name": "7 Cm Electric Sparklers",
  "price": 40,
  "image": assets.electric7cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 187,
  "name": "7 Cm Glittering Sparklers",
  "price": 45,
  "image": assets.crackling7cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 188,
  "name": "7 Cm Green Sparklers",
  "price": 55,
  "image": assets.green7cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 189,
  "name": "7 Cm Red Sparklers",
  "price": 60,
  "image": assets.red7cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Red"
},
{
  "id": 190,
  "name": "10 Cm Electric Sparklers",
  "price": 75,
  "image": assets.electric10cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 191,
  "name": "10 Cm Glittering Sparklers",
  "price": 80,
  "image": assets.crackling10cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 192,
  "name": "10 Cm Green Sparklers",
  "price": 90,
  "image": assets.green10cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 193,
  "name": "10 Cm Red Sparklers",
  "price": 100,
  "image": assets.red10cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Red"
},
{
  "id": 194,
  "name": "12 Cm Electric Sparklers",
  "price": 110,
  "image": assets.electric12cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 195,
  "name": "12 Cm Glittering Sparklers",
  "price": 120,
  "image": assets.crackling12cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 196,
  "name": "12 Cm Green Sparklers",
  "price": 130,
  "image": assets.green12cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 197,
  "name": "12 Cm Red Sparklers",
  "price": 140,
  "image": assets.red12cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Red"
},
{
  "id": 198,
  "name": "15 Cm Electric Sparklers",
  "price": 190,
  "image": assets.electric15cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 199,
  "name": "15 Cm Glittering Sparklers",
  "price": 195,
  "image": assets.crackling15cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 200,
  "name": "15 Cm Green Sparklers",
  "price": 200,
  "image": assets.green15cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 201,
  "name": "15 Cm Red Sparklers",
  "price": 220,
  "image": assets.red15cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Red"
},
{
  "id": 202,
  "name": "30 Cm Electric Sparklers",
  "price": 190,
  "image": assets.electric30cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 203,
  "name": "30 Cm Glittering Sparklers",
  "price": 195,
  "image": assets.crackling30cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 204,
  "name": "30 Cm Green Sparklers",
  "price": 200,
  "image": assets.green30cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 205,
  "name": "30 Cm Red Sparklers",
  "price": 220,
  "image": assets.red30cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Red"
},
{
  "id": 206,
  "name": "30 Cm Hulk Sparklers",
  "price": 800,
  "image": assets.hulk,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 207,
  "name": "Captain America",
  "price": 300,
  "image": assets.captain,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 208,
  "name": "30 Cm Electric (Water Proof)",
  "price": 230,
  "image": assets.Royal30Electric,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 209,
  "name": "30 Cm Glittering (Water Proof)",
  "price": 250,
  "image": assets.water30cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 210,
  "name": "50 Cm Electric Sparklers",
  "price": 900,
  "image": assets.electric50cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 211,
  "name": "50 Cm Multi Colour Sparklers",
  "price": 1000,
  "image": assets.color50cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Multi Colour"
},
{
  "id": 212,
  "name": "50 Cm Green Sparklers",
  "price": 1100,
  "image": assets.crackling50cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 213,
  "name": "50 Cm Electric (Water Proof)",
  "price": 950,
  "image": assets.electric50cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 214,
  "name": "50 Cm Glittering (Water Proof)",
  "price": 1000,
  "image": assets.crackling50cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Glittering"
},
{
  "id": 215,
  "name": "75 Cm Electric Sparklers",
  "price": 1200,
  "image": assets.electric75cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Electric"
},
{
  "id": 216,
  "name": "75 Cm Green Sparklers",
  "price": 1300,
  "image": assets.green75cm,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Green"
},
{
  "id": 217,
  "name": "Rotating Sparklers",
  "price": 950,
  "image": assets.rotating,
  "category": "SPARKLERS",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 218,
  "name": "Eifel Towers (1Pce)",
  "price": 1000,
  "image": assets.efil,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 219,
  "name": "Danis (1Pce)",
  "price": 1000,
  "image": assets.danis,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 220,
  "name": "Helsmiki (1Pce)",
  "price": 1000,
  "image": assets.helsimki,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 221,
  "name": "Spain (2 Pce)",
  "price": 2000,
  "image": assets.spain,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 222,
  "name": "Denmark (2 Pce)",
  "price": 2000,
  "image": assets.denmark,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 223,
  "name": "Finland (2 Pce)",
  "price": 2000,
  "image": assets.finland,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 224,
  "name": "Poland (2 Pce)",
  "price": 2000,
  "image": assets.poland,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 225,
  "name": "Paris (2 Pce)",
  "price": 2000,
  "image": assets.paris,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 226,
  "name": "Gold Card Member (2Pce)",
  "price": 2800,
  "image": assets.goldcard,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 227,
  "name": "Orange (2Pce)",
  "price": 2800,
  "image": assets.orange,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 228,
  "name": "Narnda (2Pce)",
  "price": 2800,
  "image": assets.narnia,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 229,
  "name": "Kalidoscope (2Pce)",
  "price": 2800,
  "image": assets.kalid,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 230,
  "name": "Lalkila (2Pce)",
  "price": 2800,
  "image": assets.lal,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 231,
  "name": "Blue Berry (2Pce)",
  "price": 2800,
  "image": assets.blueberry,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 232,
  "name": "Golden Chip (2Pce)",
  "price": 2800,
  "image": assets.goldenchip,
  "category": "2½ PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 233,
  "name": "Night Angels (2 Piece)",
  "price": 3800,
  "image": assets.nightangel,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 234,
  "name": "Infra Red (2 Piece)",
  "price": 3800,
  "image": assets.infra,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 235,
  "name": "Yellow Showers (2 Piece)",
  "price": 3800,
  "image": assets.yellow,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 236,
  "name": "Green Valley (2 Piece)",
  "price": 3800,
  "image": assets.vally,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 237,
  "name": "Lal Mirchi (2 Piece)",
  "price": 3800,
  "image": assets.mirchi,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 238,
  "name": "Golden Angles (2 Piece)",
  "price": 3800,
  "image": assets.angel,
  "category": "3\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 239,
  "name": "Blue Chip (2 Piece)",
  "price": 4500,
  "image": assets.bluechip,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 240,
  "name": "Golden Octopus (2 Piece)",
  "price": 4500,
  "image": assets.octo,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 241,
  "name": "Neela Angel (2 Piece)",
  "price": 4500,
  "image": assets.neela,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 242,
  "name": "Warrier Angel (2 Piece)",
  "price": 4500,
  "image": assets.neela,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 243,
  "name": "Vertigo (Pink Colour) (2 Piece)",
  "price": 4500,
  "image": assets.vertigo,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Pink"
},
{
  "id": 244,
  "name": "Monster (2 Piece)",
  "price": 4500,
  "image": assets.monster,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 245,
  "name": "Cactus Rain (2 Piece)",
  "price": 5000,
  "image": assets.rain,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 246,
  "name": "Mela (2 Piece)",
  "price": 5000,
  "image": assets.mela,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 247,
  "name": "Rock N Roll (2 Piece)",
  "price": 5000,
  "image": assets.rock,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 248,
  "name": "Naya Naya Pyar (2 Piece)",
  "price": 5000,
  "image": assets.naya,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 249,
  "name": "Hot Mirchi (2 Piece)",
  "price": 5000,
  "image": assets.hot,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 250,
  "name": "Bad Boys (2 Piece)",
  "price": 5000,
  "image": assets.badboy,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 251,
  "name": "2000 Bugs (2 Piece)",
  "price": 5000,
  "image": assets.bugs,
  "category": "3½\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 252,
  "name": "Blue Heaven (2 Piece)",
  "price": 5000,
  "image": assets.heaven,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Blue"
},
{
  "id": 253,
  "name": "Magic Crystle (2 Piece)",
  "price": 5000,
  "image": assets.crystle,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 254,
  "name": "World War (2 Piece)",
  "price": 5000,
  "image": assets.worldwar,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 255,
  "name": "Sky Traffic (2 Piece)",
  "price": 5000,
  "image": assets.skytraffic,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 256,
  "name": "Bollywood (2 Piece)",
  "price": 5000,
  "image": assets.bolly,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 257,
  "name": "Velvet (2 Piece)",
  "price": 5000,
  "image": assets.velvet,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 258,
  "name": "Lemon (2 Piece)",
  "price": 5000,
  "image": assets.lemon,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 259,
  "name": "Blue Octopus (2 Piece)",
  "price": 5000,
  "image": assets.blueocto,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Blue"
},
{
  "id": 260,
  "name": "Golden Web (2 Piece)",
  "price": 5000,
  "image": assets.web,
  "category": "4\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": "Golden"
},
{
  "id": 261,
  "name": "7th Sense (2 Piece)",
  "price": 6000,
  "image": assets.sense,
  "category": "5\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 262,
  "name": "X man (2 Piece)",
  "price": 6000,
  "image": assets.xman,
  "category": "5\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 263,
  "name": "Bruce Lee (2 Piece)",
  "price": 6000,
  "image": assets.brucelee,
  "category": "5\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 264,
  "name": "Hercules (2 Piece)",
  "price": 6000,
  "image": assets.hercules,
  "category": "5\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 265,
  "name": "Colour Plus (2 Piece)",
  "price": 6000,
  "image": assets.colourplus,
  "category": "5\" PIPE (SONY)",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 266,
  "name": "MIB (Sony)",
  "price": 450,
  "image": assets.menin,
  "category": "KIDS SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 267,
  "name": "Pirates (Sony)",
  "price": 850,
  "image": assets.pirate,
  "category": "KIDS SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 268,
  "name": "Terminator (Sony)",
  "price": 1750,
  "image": assets.terminator,
  "category": "KIDS SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 269,
  "name": "Ring Cap (Sony)",
  "price": 40,
  "image": assets.ring,
  "category": "KIDS SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 270,
  "name": "Pop-Pop",
  "price": 1500,
  "image": assets.poppop,
  "category": "KIDS SPECIAL",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 271,
  "name": "Super Deluxe",
  "price": 450,
  "image": assets.robin,
  "category": "MATCH BOX",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 272,
  "name": "Lumba",
  "price": 750,
  "image": assets.dummy,
  "category": "MATCH BOX",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 273,
  "name": "Royal Max Laptop",
  "price": 1000,
  "image": assets.royalmax,
  "category": "MATCH BOX",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 274,
  "name": "Royal Maga Laptop",
  "price": 1200,
  "image": assets.royalmega,
  "category": "MATCH BOX",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 275,
  "name": "20 Items",
  "price": 275,
  "image": assets.gift20,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 276,
  "name": "25 Items",
  "price": 350,
  "image": assets.gift25,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 277,
  "name": "31 Items",
  "price": 400,
  "image": assets.gift311,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 278,
  "name": "36 Items",
  "price": 500,
  "image": assets.gift361,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 279,
  "name": "41 Items",
  "price": 700,
  "image": assets.gift411,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 280,
  "name": "51 Items",
  "price": 850,
  "image": assets.gift51,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},
{
  "id": 281,
  "name": "61 Items",
  "price": 1150,
  "image": assets.gift61,
  "category": "Gift Box",
  "brand": "MANO",
  "rating": null,
  "description": null,
  "color": null
},

  ];
