export const CATEGORIES = [
  { id: 'all', name: 'All' },
  { id: 'Gift Box', name: 'Gift Box'},
  { id: 'MATCH BOX', name: 'MATCH BOX'},
  { id: 'KIDS SPECIAL', name: 'KIDS SPECIAL'},
  { id: '5\" PIPE (SONY)', name: '5\" PIPE (SONY)'},
  { id: '4\" PIPE (SONY)', name: '4\" PIPE (SONY)'},
  { id: '3½\" PIPE (SONY)', name: '3½\" PIPE (SONY)'},
  { id: '3\" PIPE (SONY)', name: '3\" PIPE (SONY)' },
  { id: '2½ PIPE (SONY)', name: '2½ PIPE (SONY)' },
  { id: 'SPARKLERS', name: 'SPARKLERS' },
  { id: 'SIREN', name: 'SIREN' },
  { id: 'MARRIAGE PARTY SPECIAL', name: 'MARRIAGE PARTY SPECIAL' },
  { id: 'PARTY SPECIAL (4 x 5 Sony)', name: 'PARTY SPECIAL (4 x 5 Sony)' },
  { id: 'NEW ARRIVALS', name: 'NEW ARRIVALS' },
  { id: 'MULTI COLOUR SHOTS', name: 'MULTI COLOUR SHOTS' },
  { id: 'REPEATING SHOT', name: 'REPEATING SHOT' },
  { id:  "5'FANCY SINGLE POE", name:  "5'FANCY SINGLE POE" },
  { id: '4\" DOUBLE BALL', name: '4\" DOUBLE BALL' },
  { id: '4\"SPECIAL COLOUR (Wow Star)', name: '4\"SPECIAL COLOUR (Wow Star)' },
  { id: '4\"FANCY 2 PIECE (Spanka)",', name: '4\"FANCY 2 PIECE (Spanka)",' },
  { id: '4\"FANCY (2 Pce Kaniskar)', name: '4\"FANCY (2 Pce Kaniskar)' },
  { id: '3½\"FANCY (Single Pce)', name: '3½\"FANCY (Single Pce)' },
  { id: '3\" FANCY (4 in 1) 3 Piece', name: '3\" FANCY (4 in 1) 3 Piece' },
  { id: '2\"FANCY (3 Pce)', name: '2\"FANCY (3 Pce)' },
  { id: '2\" SINGLE FANCY (3 Pce)', name: '2\" SINGLE FANCY (3 Pce)' },
  { id: '1% CHOTA FANCY (3 Pce)', name: '1% CHOTA FANCY (3 Pce)' },
  { id: 'CHOTA FANCY (Single Pce)', name: 'CHOTA FANCY (Single Pce)' },
  { id: 'SMOKE', name: 'SMOKE' },
  { id: 'SNAKE TABLET', name: 'SNAKE TABLET' },
  { id: 'NOVELTIES', name: 'NOVELTIES' },
  { id: 'BIJILI', name: 'BIJILI' },
  { id: 'ROCKET', name: 'ROCKET' },
  { id: 'WATER QUEEN', name: 'WATER QUEEN' },
  { id: 'TRI COLOUR FOUNTAIN', name: 'TRI COLOUR FOUNTAIN' },
  { id: 'MULTI COLOUR SHOTS', name: 'MULTI COLOUR SHOTS' },
  { id: 'PEACOCK FOUNTAIN', name: 'PEACOCK FOUNTAIN' },
  { id: 'BOMBS', name: 'BOMBS' },
  { id: 'CHIT PUT', name: 'CHIT PUT' },
  { id: 'TWINKLING STAR', name: 'TWINKLING STAR' },
  { id: 'GROUND CHAKKAR', name: 'GROUND CHAKKAR' },
  { id: 'FLOWER POTS', name: 'FLOWER POTS' },
  { id: 'ONE SOUND CRACKERS', name: 'ONE SOUND CRACKERS' },
  
];



export const ANIMATION_COLORS = [
  '#ff6b6b', 
  '#4ecdc4', 
  '#45b7d1', 
  '#f9ca24', 
  '#f0932b', 
  '#eb4d4b', 
  '#6c5ce7', 
  '#a29bfe'
];